update dependency ui kit and storybook
rispa-io/rispa-ui-kit pull request #20
Opened 2019-01-18 14:06 UTC by dmitrbrvsk

2019-01-18 14:14 UTC, Fyzu requested changes
Еще нужно мигрировать генераторы для атомов и молекул

2019-01-18 14:14 UTC, Fyzu commented on .storybook/webpack.config.js
> +      "@babel/preset-env",
Тут надо было указать наш пресет

2019-01-18 14:14 UTC, Fyzu commented on .storybook/webpack.config.js
> +          test: /\.stories\.jsx?$/,
он разве не реализован в baseConfig?

2019-01-21 10:00 UTC, dmitrbrvsk commented on .storybook/webpack.config.js
> +          test: /\.stories\.jsx?$/,
@Fyzu это нужно для вызова декоратора `addon-storysource` для каждой сторис

2019-01-21 10:01 UTC, dmitrbrvsk commented on .storybook/webpack.config.js
> +      "@babel/preset-env",
поправил

2019-01-21 10:53 UTC, Fyzu requested changes
Change dest. branch to `next`

2019-01-25 08:37 UTC, Fyzu approved these changes

2019-01-25 08:37 UTC, merged